### ISSUE TITLE
RadLoopingList has un wanted rectangles in content presenter

### ISSUE THREAD

**Issue by touseefbsb** [telerik/UI-For-UWP#132]
I am trying to make a horizontal looping list, in which I want to put some custom Data Template. with each item will have Image, and some text blocks. My question is why are there 2 rectangles along with the content of the item? I don't want those rectangles I want my looping list to act like a normal uwp listview, in terms of content. where I can have custom content in data template with out those rectangles. Please let me know how can I edit the style of items so that I can remove those rectangles. I have tried to set custom template of LoopingListItem Style to "ItemStyle" property but the app crashes on this attempt

**Comment by APopatanasov** [comment]
Hi @touseefbsb ,

The Rectangles are part of the design of the LoopingListItems and are needed for the accurate and expected visualization of the items when they are selected. As you have found out in order to change the default appearance the default Template of the items could be changed using the ItemStyle. An example that demonstrates how the ItemStyle could be used you could find [here](https://github.com/telerik/UI-For-UWP/blob/master/SDKExamples.UWP/Examples/LoopingList/Customizations.xaml). 

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased [a commercial license for UI for UWP](http://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed. You'll be directed to post your question on a community forum.
