### ISSUE TITLE
Doesn't RadDataForm support DateTimeOffset?

### ISSUE THREAD

**Issue by imnbwd** [telerik/UI-For-UWP#142]
There is a property which type is DateTimeOffset in one of my model classes, and when I set this model to the Item property of RadDataForm, however, only that property cannot be shown in the form.

**Comment by APopatanasov** [comment]
Hi @imnbwd ,
The RadDataForm does not supports the DateTimeOffset type out of the box and because of that it doesn't create EntityPropertyControl for it. You could register a custom editor for it using the RegisterTypeEditor method.

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased [a commercial license for UI for UWP](http://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed. You'll be directed to post your question on a community forum.
