### ISSUE TITLE
Broken CartesianChart Grid Lines

### ISSUE THREAD

**Issue by jmvillagra** [telerik/UI-For-UWP#144]
Using the latest code and the SDKExamples.UWP, the grid lines doesn't show up in the Ohlc Series Charts.
It's easily reproducible just adding to the OhlcSeries.xaml file the corresponding lines section:

```
<chart:RadCartesianChart>
	<chart:RadCartesianChart.DataContext>
		<localChart:ViewModelOhlc/>
	</chart:RadCartesianChart.DataContext>
	<chart:OhlcSeries ItemsSource="{Binding Source}">
		<chart:OhlcSeries.HorizontalAxis>
			<chart:CategoricalAxis/>
		</chart:OhlcSeries.HorizontalAxis>
		<chart:OhlcSeries.VerticalAxis>
			<chart:LinearAxis/>
		</chart:OhlcSeries.VerticalAxis>
		<chart:OhlcSeries.HighBinding>
			<chart:PropertyNameDataPointBinding PropertyName="High"/>
		</chart:OhlcSeries.HighBinding>
		<chart:OhlcSeries.LowBinding>
			<chart:PropertyNameDataPointBinding PropertyName="Low"/>
		</chart:OhlcSeries.LowBinding>
		<chart:OhlcSeries.OpenBinding>
			<chart:PropertyNameDataPointBinding PropertyName="Open"/>
		</chart:OhlcSeries.OpenBinding>
		<chart:OhlcSeries.CloseBinding>
			<chart:PropertyNameDataPointBinding PropertyName="Close"/>
		</chart:OhlcSeries.CloseBinding>
	</chart:OhlcSeries>
	<chart:RadCartesianChart.Grid>
		<chart:CartesianChartGrid MajorLinesVisibility="XY" />
	</chart:RadCartesianChart.Grid>
</chart:RadCartesianChart>
```

![image](https://user-images.githubusercontent.com/4366478/27902559-746d970a-6236-11e7-95a9-4caa344bbc29.png)

Tested with windows version 1703

**Comment by APopatanasov** [comment]
Hi @jmvillagra ,
Could you please confirm that is has been working with an older version of the controls as we are reproducing with much older version?

**Comment by jmvillagra** [comment]
Can't confirm it as I've just started using the library

**Comment by APopatanasov** [comment]
@jmvillagra after further investigation of the Chart's XAML declaration we were able to find the the reason why the Grid Lines are not visualized. In order to to be able to draw the lines the Chart should has its primary Horizonal and Vertical axes defined:
`<telerikChart:RadCartesianChart.HorizontalAxis>
    <telerikChart:CategoricalAxis/>
</telerikChart:RadCartesianChart.HorizontalAxis>
<telerikChart:RadCartesianChart.VerticalAxis>
    <telerikChart:LinearAxis/>
</telerikChart:RadCartesianChart.VerticalAxis>`

If only the secondary axes (the one of the series) are defined the ChartGrid couldn't be drawn. Please, define axes for the Chart in order to make everything be visualized as expected.

As this is a declaration we have used in our SDK examples we will change it so, every Chart has its primary axes defined. 

Hopes this information will be helpful for you.

**Comment by jmvillagra** [comment]
Yes, that was it. Now it works perfectly.
Thanks
