### ISSUE TITLE
When DataGrid ItemSource is refreshed hitting NullReferenceException after few click on edit mode.

### ISSUE THREAD

**Issue by abralock** [telerik/UI-For-UWP#189]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Telerik.UI.Xaml.Controls.Grid.DataGridTypedColumn.OnCellValidating(Object sender, ValidatingEventArgs e)
   at Telerik.UI.Xaml.Controls.Primitives.ValidationControl.OnValidating(IList`1 currentErrors)
   at Telerik.UI.Xaml.Controls.Primitives.ValidationControl.ValidateCore(Boolean async, Boolean forceValidate)
   at Telerik.UI.Xaml.Controls.Primitives.ValidationControl.OnDataItemChanged(DependencyObject d, Depende

**Comment by abralock** [comment]
I develop my app using MVVM, which bind my ObservableCollection from view model to view.  After I refreshed my item source basically with clear ObservableCollection then reinsert again records as general. The grid is refreshed but somehow a few click on edit mode afterwards it will throw exception as above.

**Comment by APopatanasov** [comment]
Hi @abralock ,

Using the provided description and stack trace I have tried to reproduce the observed exception, but it seems everything is working as expected.

Attached you can find the sample I used for my investigation. Could you please, try to modify it with your exact setup in order to reproduce the exception and send it back to me?

I am looking forward for your reply.
[App6.zip](https://github.com/telerik/UI-For-UWP/files/1369798/App6.zip)

**Comment by abralock** [comment]
Sure, let me did that. Will update you soon.

**Comment by APopatanasov** [comment]
Hi @abralock ,

Is there any progress with the isolation of the issue?

**Comment by abralock** [comment]
Hi APopatanasov,

I manage to solve by self on this. Please close the issue. Thanks.

Abraham
