### ISSUE TITLE
RadDataGrid's external editor ignores the CanUserEdit property of DataGridTextColumn

### ISSUE THREAD

**Issue by WDev20** [telerik/UI-For-UWP#211]
Hi,

I've the RadDataGrid configured as follows, but the external editor ignores the CanUserEdit property when set to false, this is not the case with the inline editor which properly disables the editor when CanUserEdit is set to false:

```
 <telerik:RadDataGrid x:Name="radGrid"
                             ColumnDataOperationsMode="Flyout"
                             GridLinesVisibility="None"
                             GroupPanelPosition="Left"
                             AutoGenerateColumns="False"
                             ColumnResizeHandleDisplayMode="Always"
                             SelectionMode="Single"
                             UserEditMode="External" 
                             Grid.ColumnSpan="2" Grid.Row="3" >
            <telerik:RadDataGrid.Columns>
                <telerik:DataGridTextColumn PropertyName="Id" CanUserFilter="False" CanUserSort="False" CanUserEdit="False"/>
                <telerik:DataGridTextColumn PropertyName="MSISDN" CanUserEdit="False"/>
                <telerik:DataGridTextColumn PropertyName="SerialNo"/>
                <telerik:DataGridTextColumn PropertyName="OfferName"/>
                <telerik:DataGridTextColumn PropertyName="DateUnlocked"/>
                <telerik:DataGridTextColumn PropertyName="Status"/>
                <telerik:DataGridTextColumn PropertyName="Error" CanUserEdit="False" />
                <telerik:DataGridTextColumn PropertyName="Subscriber"/>
                <telerik:DataGridTextColumn PropertyName="SIMUnlockDateLocalTime"/>
            </telerik:RadDataGrid.Columns>

        </telerik:RadDataGrid>
```
Here is what appears with external editor:
![issue](https://user-images.githubusercontent.com/34504738/34269890-64da3a12-e686-11e7-8ac9-229074447248.GIF)

And here is what shows up with inline editor:

![issue3](https://user-images.githubusercontent.com/34504738/34269870-513a8c6e-e686-11e7-954b-65463e5a2939.GIF)

**Comment by APopatanasov** [comment]
Hi @WDev20 ,

I can confirm that the observed by you behavior with the external editor mode is not an expected one. I agree that the CanUserEdit property should be connected with the DataForm that visualizes the editors. As this is a scenario that has not been planned for implementation I will mark the issue as a feature and I am open to any suggestions what is the best way to implement it - feel free to make a pull request and I will be glad to review it.

For now what you can do in order to achieve the desired is to mark the property you don't want to edit with the **ReadOnly** attribute - for example:
`
[Telerik.Data.Core.ReadOnly]
public int Age
{
    get { return age; }
    set
    {
        if (age != value)
        {
            age = value;
            OnPropertyChanged();
        }
    }
}
`
The DataForm will disable the editor when that attribute is set for the specific property.

Hope this will be helpful for you.

**Comment by WDev20** [comment]
Hi @APopatanasov,

Thanks for your suggestion which seems reasonable, but why isn't the RuntimeEntityProperty depending on the metadata attributes provided by the System.ComponentModel namespace instead?

**Comment by APopatanasov** [comment]
@WDev20 This was an implementation decision taken by the development team while working on the DataForm control. I hope using that built-in specific attribute for the DataForm is not causing any inconveniences for you.

**Comment by WDev20** [comment]
Hi @APopatanasov,
Thanks for the calrification. 

I tried adding the ReadOnlyAttribute to the Id property, I accidently switched back to the inline editor, but this time that editor ignored it unless CanUserEdit is explicitly set to false.

I cannot find the implementation of inline editor to investigate the problem. Could you please direct me the source files?

**Comment by APopatanasov** [comment]
Hi @WDev20 ,

The attribute is only working for the external editor because the external editor is using the DataForm control - that attribute indicates the DataForm that the editor (the NumericEditor in your case) should be read only. 

For the inline editors there is separate logic for their generation and for that mode the CanUserEdit property should still be set to false - both your logic to be working as expected you need to have the attribute and the property set to false. The approach with the attribute was suggested only to resolve the missing implementation of the external editor.

Still, if you are interested of the generation of the editors for the inline edit mode check the PrepareEditorContainer method for the specific columns. Here is the method for the base class DataGridTypedColumn:
https://github.com/telerik/UI-For-UWP/blob/0d139af06e2a2d9cd87266faeeed03330aed5fc7/Controls/Grid/Grid.UWP/View/Columns/TypedColumns/DataGridTypedColumn.cs#L300

Hope this information will be helpful for you.
