### ISSUE TITLE
The first point of RangeSeries is not rendered

### ISSUE THREAD

**Issue by snrnats** [telerik/UI-For-UWP#244]
The first point and connecting lines of RangeSeries are not rendered. 
The issue is reproducible since 1.0.0.7. So it's because of 224f93ee11f32e39b404074f26c8c8b2f8ca3cea
Here is a test project
[TelerikRangeSeriesChart.zip](https://github.com/telerik/UI-For-UWP/files/1720067/TelerikRangeSeriesChart.zip)
or xaml:
```
<chart:RadCartesianChart PaletteName="DefaultLight">
            <chart:RadCartesianChart.HorizontalAxis>
                <chart:DateTimeCategoricalAxis LabelFormat="{}{0:d MMM}"/>
            </chart:RadCartesianChart.HorizontalAxis>
            <chart:RadCartesianChart.VerticalAxis>
                <chart:LinearAxis/>
            </chart:RadCartesianChart.VerticalAxis>
            <chart:RangeSeries x:Name="RangesSeries">
                <chart:RangeSeries.CategoryBinding>
                    <chart:PropertyNameDataPointBinding PropertyName="Date"/>
                </chart:RangeSeries.CategoryBinding>
                <chart:RangeSeries.LowBinding>
                    <chart:PropertyNameDataPointBinding PropertyName="Low"/>
                </chart:RangeSeries.LowBinding>
                <chart:RangeSeries.HighBinding>
                    <chart:PropertyNameDataPointBinding PropertyName="High"/>
                </chart:RangeSeries.HighBinding>
            </chart:RangeSeries>
        </chart:RadCartesianChart>
```
![applicationframehost_2018-02-13_16-34-39](https://user-images.githubusercontent.com/1597284/36152459-3487ce4e-10dc-11e8-9970-b9d550121ba3.png)

**Comment by APopatanasov** [comment]
Hi @snrnats ,

Indeed the mentioned commit has introduced the observed behavior for the RangeSeries. However, the fix itself is very important and fixes a major performance issue in the Chart.

After investigating a little bit the code of the RangeSeries I believe not rendering that first point is caused by the logic of the series itself. The first point that needs to be rendered has a negative X coordinate because of that it gets skip from rendering. I could not be 100 percent sure if that negative value is expected.

What we could do now for fixing this for that RangeSeries is to override the GetRenderPoints method inside the [RangeRenderer ](https://github.com/telerik/UI-For-UWP/blob/master/Controls/Chart/Chart.UWP/Visualization/Common/Renderers/Cartesian/Range/RangeRenderer.cs)class and include code like:
```
protected override IList<DataPoint> GetRenderPoints()
{
    if (this.model.renderablePoints.Count > 0)
    {
        return this.model.renderablePoints.Where(a => (a.layoutSlot.X >= 0 && a.layoutSlot.Y >= 0) || a.Index == 0).ToList();
    }

    return this.model.DataPointsInternal.Where(a => (a.layoutSlot.X >= 0 && a.layoutSlot.Y >= 0) || a.Index == 0).ToList();
}
```

If this is observed in other series (which I believe it could be possible as there are many scenarios that could be missed) I should probably think of another suggestion. Could you please, let me know if there are other series where you are observing an unexpected behavior?

If you are interested on working on this issue you could make a pull request with the suggested fix and I will review it. As mentioned above the fix you could think about could be connected with the GetRenderPoints method and overiding it with a specific for the series logic inside the [RangeRenderer ](https://github.com/telerik/UI-For-UWP/blob/master/Controls/Chart/Chart.UWP/Visualization/Common/Renderers/Cartesian/Range/RangeRenderer.cs)class.

Hope the provided information will be helpful.

**Comment by snrnats** [comment]
@APopatanasov thank you for the fast response.

I've also noticed the negative X position in my example. I will try to find out the reason of it. I believe it's the issue that needs to be fixed. For now I'm not aware of any other affected series.

One more issue I found is that "Empty values" demo isn't working as expected anymore. The reason is the same block of code. In that case `a.layoutSlot.Y` is NaN that computes `a.layoutSlot.Y >= 0` as `false`.

**Comment by APopatanasov** [comment]
@snrnats Thanks for the information. I was able to observe the issue in the Empty values demo. Here you can add the additional check for NaN for the GetRenderPoints method in the ChartSeriesRenderer in order to return the right points. 

If you are interested on fixing this you can make a pull request and I will review it - if everything seems fine I will merge the PR and the fix will be available with the next nuget package that should be released soon.

Thanks again.
