### ISSUE TITLE
RadDataGrid crashes when created in a second view.

### ISSUE THREAD

**Issue by ComponentFactory** [telerik/UI-For-UWP#258]
Place a RadDataGrid with sample data in your a main view. Now add a button that when clicked creates a second view that also contains a RadDataGrid. The second instance will crash with the following error...

System.Exception: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))
at Windows.UI.Xaml.FrameworkElement.put_Style(Style value)
at Telerik.UI.Xaml.Controls.Grid.DataGridTextColumn.PrepareCell(Object container, Object value, Object item)
at Telerik.UI.Xaml.Controls.Grid.DataGridBooleanColumn.PrepareCell(Object container, Object value, Object item)
at Telerik.UI.Xaml.Controls.Grid.DataGridColumn.PrepareCell(

You can create the second view using the following same code that assumes the existence of a page called Grid1Page.

private async void Grid1_Click(object sender, Windows.UI.Xaml.RoutedEventArgs e)
{
    int newViewId = 0;
    await CoreApplication.CreateNewView().Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
    {
        Frame frame = new Frame();
        frame.Navigate(typeof(Grid1Page));
        Window.Current.Content = frame;
        Window.Current.Activate();
        newViewId = ApplicationView.GetForCurrentView().Id;
    });
    await ApplicationViewSwitcher.TryShowAsStandaloneAsync(newViewId);
}

**Comment by APopatanasov** [comment]
Hi @ComponentFactory , 

Using the provided description and code-snippet for navigation I tried to reproduce the observed exception, but without any luck. Attached you can find the sample project I used for my investigation. Could you please, modify it in order to reproduce the exception and send it back to me? Thus I will be able continue the investigation and provide you with more detailed information what might be causing the exception.

I am looking forward to hearing from you.
[RadDataGrid_258.zip](https://github.com/telerik/UI-For-UWP/files/1850885/RadDataGrid_258.zip)

**Comment by ComponentFactory** [comment]
Thanks for the quick response and the sample application. 

You sample project targets version 15063 (November Update) of Windows 10 and works fine on my machine. 

But if you update the project properties to target 16299 (Fall Creators Update) then it crashes every time. So it would seem that the issue is exposed on the latest update.

Thanks.

**Comment by APopatanasov** [comment]
@ComponentFactory Thanks for the provided information. I was able to reproduce the exception and found what is causing it. With 16299 the Style class is now holding a Dispatcher in its implementation. Because of that when a new view/UI thread is created the Styles that the Grid is using in that second page are static and belong to the first UI thread and because of that the exception is thrown - as mentioned above[ with 16299 the Styles are thread specific and hold instance to the CoreDispatche](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.style#properties-)r and that causes the exception.

In order the issue to be fixes all Styles static fields used in the DataGridColumns should be replaced with non-static. For example in the DataGridTextColumn the Styles should not be static:
https://github.com/telerik/UI-For-UWP/blob/d2ffa05c4ec9bae4737ac77236457bef74bb090d/Controls/Grid/Grid.UWP/View/Columns/TypedColumns/DataGridTextColumn.cs#L23

If you are interested on working on this issue you could check all TypedColumns using static Styles and replace them with non-static:
https://github.com/telerik/UI-For-UWP/tree/master/Controls/Grid/Grid.UWP/View/Columns/TypedColumns

In the meantime as a workaround you could declare all the columns you are using in Xaml and set their   CellContentStyle:
`<grid:DataGridTextColumn PropertyName="Country">
    <grid:DataGridTextColumn.CellContentStyle>
        <Style TargetType="TextBlock">
            <Setter Property="Foreground" Value="Red"/>
        </Style>
    </grid:DataGridTextColumn.CellContentStyle>
</grid:DataGridTextColumn>`

In that way the default static Styles won't be applied and no exception should be observed.

I hope this will help you.
