### ISSUE TITLE
RadChart occurs exception when displayed on multiple windows.

### ISSUE THREAD

**Issue by jz5** [telerik/UI-For-UWP#288]
RadCartesianChart occurs an exception when it is displayed twice or in two Pages in multiple windows.

```
System.Exception: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))
   at Windows.UI.Xaml.Media.SolidColorBrush.get_Color()
   at Telerik.UI.Xaml.Controls.Chart.ContainerVisualsFactory.SetCompositionColorBrush(ContainerVisual containerVisual, Brush brush, Boolean isInternallyChanged)
   at Telerik.UI.Xaml.Controls.Chart.ContainerVisualsFactory.PreparePointTemplateSeriesVisual(ContainerVisual containerVisual, DataPoint
```

[The minimum project for reproduce](https://github.com/jz5/RadChartApp1).

**Comment by APopatanasov** [comment]
@jz5 The observed by you exception is caused by the fact the SolidColorBrush itself is holding a Dispatcher. Because of that when a new view/UI thread is created the Brush that was initially created in the first page belongs to it and accessing its color from the second page throws the observed exception. As a fix in the controls the only possible solution is to invoke the code that gets the Color of the Brush from withing a Dispatcher - that way the Color will be taken from the main UI thread:
`else if (solidColorBrush != null)
{
    await brush.Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () =>
    {
        var compositionColorBrush = spriteVisual.Brush as CompositionColorBrush;
        if (compositionColorBrush == null)
        {
            spriteVisual.Brush = spriteVisual.Compositor.CreateColorBrush(solidColorBrush.Color);
            spriteVisual.Opacity = (float)solidColorBrush.Opacity;
        }
        else if (compositionColorBrush != null && compositionColorBrush.Color != solidColorBrush.Color && isInternallyChanged)
        {
            spriteVisual.Brush = spriteVisual.Compositor.CreateColorBrush(solidColorBrush.Color);
            spriteVisual.Opacity = (float)solidColorBrush.Opacity;
        }
    });
}`

That code is found [here](https://github.com/telerik/UI-For-UWP/blob/2940a12f10527c564e5657fd92428656ebbb7dad/Controls/Chart/Chart.UWP/Visualization/Common/ContainerVisualsFactory.cs#L41).

If you are interested on working on this issue you can make a pull request with the mentioned above fix and I will review it.

For your project you can also apply a workaround. Instead of drawing the bars with the Composition mechanism you can disable it by creating a custom ContainerVisualsFactory and override the CanDrawContainerVisual to return false. I have modified your sample with the described approach - please, check it.

I hope the provided information will be helpful for you.
[RadChartApp1.zip](https://github.com/telerik/UI-For-UWP/files/2105309/RadChartApp1.zip)
