### ISSUE TITLE
Linear Gradient Palettes Not Showing on Runtime

### ISSUE THREAD

**Issue by jeffgonzaga** [telerik/UI-For-UWP#291]
I created a custom palette for my bar chart. I added some LinearGradientBrush. These gradient brushes render on design time however it doesn't show when I ran my app. It seems only solid gradient brush is supported.
![gradient](https://user-images.githubusercontent.com/18494324/41788581-9d1efb6e-767e-11e8-8643-fd26b531589e.PNG)
![non-gradient](https://user-images.githubusercontent.com/18494324/41788582-9d5f6460-767e-11e8-91cb-47a1970c3e5e.PNG)

**Comment by APopatanasov** [comment]
Hi @jeffgonzaga ,

The BarSeries in the Chart control has two mechanisms for rendering. The first one (which is the default one) is using the Composition API of Microsoft for rendering the bars. That mechanism boosts the performance of the BarSeries a lot when there is a great amount of items (bars). The second mechanism is the one that uses native visual elements like Border to draw the BarSeries. 

When the first mechanism was implemented the type of Brush provided by the Composition API was only one - using a solid color. Because of that when you try to set a Gradient brush it doesn't get visualized as expected. I have checked the recent releases of the Composition API and it seems now t[he API has a support for Gradient brushes](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositiongradientbrush) introduced recently with the Falls Creators update. Because of that I will mark your issues as a feature request for improving the described above mechanism to use gradient brushes.

For now what I can suggest you in order to achieve the desired visualization is to use the second mechanisms of drawing the BarSeries. Basically you need to create a custom class that inherits from **ContainerVisualsFactory** class and override its **CanDrawContainerVisual** method to return **false**:
`public class CustomContainerVisualFactory : ContainerVisualsFactory
{
    protected override bool CanDrawContainerVisual(PresenterBase visualElement)
    {
        return false;
    }
}`

After that you need to assign that as a value to the ContainerVisualsFactory property of the Chart:
`<telerikChart:RadCartesianChart.ContainerVisualsFactory>
    <local:CustomContainerVisualFactory/>
</telerikChart:RadCartesianChart.ContainerVisualsFactory>`

Thus the series will be drawn using the Border visual elements and the gradient brushes will be applied as expected. I **have created a sample project that demonstrates the described above approach - please, check it.**

If you are interested on working on this feature the place where the brushes are applied to the Composition visual is inside the SetCompositionColorBrush in the ContainerVisualsFactory class:
https://github.com/telerik/UI-For-UWP/blob/2940a12f10527c564e5657fd92428656ebbb7dad/Controls/Chart/Chart.UWP/Visualization/Common/ContainerVisualsFactory.cs#L31

That method should be improved so its implementation to be able to handle now the new CompositionGradientBrush - please, be aware that in order to use that API the projects should target at least Falls Creators update because the brush was introduced with it. This is a great start point for building that feature. If you agree to work on it and have questions you can always constant me. I will be glad to help. 
[RadChartUWP_291.zip](https://github.com/telerik/UI-For-UWP/files/2130000/RadChartUWP_291.zip)

**Comment by jeffgonzaga** [comment]
@APopatanasov 

Thanks for the info. I able to implement the CompositionGradientBrush as you have mentioned. So far, I was able to achieve what I wanted. Here's a the code of what I did:


```
internal void SetCompositionColorBrush(ContainerVisual containerVisual, Brush brush, bool isInternallyChanged = false)
        {
            var spriteVisual = containerVisual as SpriteVisual;
            if (spriteVisual != null)
            {
                if (brush is SolidColorBrush)
                {
                    var solidColorBrush = brush as SolidColorBrush;
                    if (solidColorBrush == null && spriteVisual.Brush != null)
                    {
                        spriteVisual.Brush = null;
                    }
                    else if (solidColorBrush != null)
                    {
                        var compositionColorBrush = spriteVisual.Brush as CompositionColorBrush;
                        if (compositionColorBrush == null)
                        {
                            spriteVisual.Brush = spriteVisual.Compositor.CreateColorBrush(solidColorBrush.Color);
                            spriteVisual.Opacity = (float)solidColorBrush.Opacity;
                        }
                        else if (compositionColorBrush != null && compositionColorBrush.Color != solidColorBrush.Color && isInternallyChanged)
                        {
                            spriteVisual.Brush = spriteVisual.Compositor.CreateColorBrush(solidColorBrush.Color);
                            spriteVisual.Opacity = (float)solidColorBrush.Opacity;
                        }
                    }
                }
                else if (brush is LinearGradientBrush)
                {
                    var gradientColorBrush = brush as LinearGradientBrush;
                    var compositor = spriteVisual.Compositor;
                    if (gradientColorBrush == null && spriteVisual.Brush != null)
                    {
                        spriteVisual.Brush = null;
                    }
                    else if (gradientColorBrush != null)
                    {
                        var gradientBrush = compositor.CreateLinearGradientBrush();
                        gradientBrush.StartPoint = gradientColorBrush.StartPoint.ToVector2();
                        gradientBrush.EndPoint = gradientColorBrush.EndPoint.ToVector2();
                        foreach (var stop in gradientColorBrush.GradientStops)
                        {
                            gradientBrush.ColorStops.Add(compositor.CreateColorGradientStop((float)stop.Offset, stop.Color));
                        }
                        spriteVisual.Brush = gradientBrush;
                    }
                }
            }
        }
```
