### ISSUE TITLE
DataGrid: The date value is not formatted correctly.

### ISSUE THREAD

**Issue by DkmS1953** [telerik/UI-For-UWP#318]
Method DateTime.Today.ToString("d") displays the string "10.09.2018".
In the DataGrid column of type DataGridDateColumn (Cellcontentformat = "{} {0.0: d}") displays "9/10/2018"

**Comment by APopatanasov** [comment]
@DkmS1953 I have checked the provided code and in both cases (inside and outside of the DataGrid) the result was "9/10/2018". On the machine I have tested this is expected because the DateTime's format is set with '/'.

In order to achieve the desired visualization of the DateTime I suggest you to set the following format:
`<grid:DataGridDateColumn PropertyName="Date" CellContentFormat="{}{0:dd.MM.yyyy}"/>`

Using it it will be sure that the separator's format won't be defined by Windows settings.

**Comment by DkmS1953** [comment]
@APopatanasov, thank you for answer. 
In Windows 10, you can independently customize the interface language, region, and data format. For example, I have an English language interface and location in the United States (to work Cortana), but  Russian data format (I live in Russia). 
Your program only considers the interface language.
And the point here is not in the separator, but in the ability to understand the output, in particular, in the possibility to distinguish the number of the day from the number of the month (e.g., "1/5/2018").
In this sense, I think that the format "{} {0, 5: dd MMM yyyy}" will be more suitable and in the line "05 Jan 2018" Problems with understanding would not arise.

Sorry for my "English"-This is Microsoft Translator

**Comment by APopatanasov** [comment]
@DkmS1953 Indeed the string is formatted using the CurrentUICulture. In order to change the format of that Culture and set to the desired one you can simple do the following:
`CultureInfo.CurrentUICulture.DateTimeFormat.ShortDatePattern = "dd MM yyyy";`

However, I suggest you to not change the default set values and simply set the desired format in the CellContentFormat as you have already did with "{} {0, 5: dd MMM yyyy}".

**Comment by DkmS1953** [comment]
Okay, I'll do it 😎
But what does "5:" mean? Where can I read more about this?

**Comment by APopatanasov** [comment]
@DkmS1953 You can check [this](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) link for some more detailed information about the formats of the DateTime.

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased [a commercial license for UI for UWP](https://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed. You'll be directed to post your question on a community forum.
