### ISSUE TITLE
How to remove the "TemplateNotAppliedException"?

### ISSUE THREAD

**Issue by yanxiaodi** [telerik/UI-For-UWP#34]
I have cloned this repository and build it for my project. I added these dlls:
* Telerik.Core.dll
* Telerik.Data.dll
* Telerik.UI.Xaml.Controls.Data.UWP.dll
* Telerik.UI.Xaml.Input.UWP.dll
* Telerik.UI.Xaml.Primitives.UWP.dll

I used the RadListView control in my project. When I run the project it throws a exception:

> {"Exception of type 'Telerik.UI.Xaml.Controls.TemplateNotAppliedException' was thrown."}

I check the source code about RadControls.cs and found some code like this:
```
       private void VerifyTemplateApplied()
        {
            if (DesignMode.DesignModeEnabled)
            {
                // TODO: This may happen in Blend
                return;
            }

            if (!this.IsTemplateApplied)
            {
                throw new TemplateNotAppliedException(this.GetType(), this.DefaultStyleKey);
            }
        }
```

The exception was thrown by this code. What is it mean?
I have already set the ItemTemplate for the RadListView control. I don't know how to resolve it. Thanks!

**Comment by APopatanasov** [comment]
Hi @yanxiaodi,
The exception is observed when some of the adjacent resources to an assembly (that include also the generic dictionaries) are not copied. Some needed files are missing and that on the other side leads to the exception. In order to resolve it you should use all of the file input including the adjacent directories - make sure that the overall structure and all of the needed files are present.

You could log an issue in our documentation repository about adding an article that provides detailed information about which files are needed when the binaries are referenced. The Repository you could find on the following link:
[https://github.com/telerik/uwp-docs](https://github.com/telerik/uwp-docs)

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased a [commercial license for UI for UWP](http://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed. You'll be directed to post your question on a community forum.

**Comment by yanxiaodi** [comment]
OK. Thanks for your reply!
