### ISSUE TITLE
Custom styling of RadDataGrid not working

### ISSUE THREAD

**Issue by byrialsen** [telerik/UI-For-UWP#349]
Hi

I am trying to override default styling of selected row(s)/cell(s) in RadDataGrid, but I believe this functionality is quite broken as is.

I have attached two gif animation showing the problems I see. I can add that I have tried it in different kind of projects (Telerik UI demo, Windows Template Studio project and my own blank project) and I see the same result for everyone.

Please note that the specific styling code can be seen in the gif's also.

![2018-11-29_22-50-28](https://user-images.githubusercontent.com/1816703/49255181-852ead80-f42b-11e8-987b-1ac1e5ec9785.gif)

![2018-11-29_22-54-55](https://user-images.githubusercontent.com/1816703/49255202-924b9c80-f42b-11e8-9bc6-227ed28bd3d7.gif)

**Comment by APopatanasov** [comment]
Hi @byrialsen ,

Actually the Background is applied as expected. However, the currency control covers it. So, basically here the issue it actually the fact the Currency control is not arranged as expected when the size of the window changes.

In order to prevent the CurrencyControl from covering the SelectionRegionBackgroundControl you can apply the following Style:
`<telerikGrid:RadDataGrid.Resources>
    <Style TargetType="primitives:SelectionRegionBackgroundControl">
        <Setter Property="Background" Value="Red"/>
        <Setter Property="BorderBrush" Value="Green"/>
        <Setter Property="BorderThickness" Value="2"/>
    </Style>
    <Style TargetType="primitives:DataGridCurrencyControl">
        <Setter Property="Visibility" Value="Collapsed"/>
    </Style>
</telerikGrid:RadDataGrid.Resources>`

Or you can simply set the same Background for the CurrencyControl:
`<telerikGrid:RadDataGrid.Resources>
    <Style TargetType="primitives:SelectionRegionBackgroundControl">
        <Setter Property="Background" Value="Red"/>
        <Setter Property="BorderBrush" Value="Green"/>
        <Setter Property="BorderThickness" Value="2"/>
    </Style>
    <Style TargetType="primitives:DataGridCurrencyControl">
        <Setter Property="Background" Value="Red"/>
    </Style>
</telerikGrid:RadDataGrid.Resources>`

Hope this helps.

**Comment by APopatanasov** [comment]
I am glad to hear the suggestions worked for you. Thanks also for your feedback. We will try to improve the documentation to cover scenarios like yours. 👍

**Comment by byrialsen** [comment]
I know you closed the issue @APopatanasov, but I still think that it could be more ideal to make the selected background brush/color work out of the box like all the other brushes used for styling the DataGrid. But maybee I am just not getting the big picture.😃
