### ISSUE TITLE
DataGridColumn.IsVisible changes not working

### ISSUE THREAD

**Issue by byrialsen** [telerik/UI-For-UWP#350]
Hi

I have a column in a `RadDataGrid` that I want to show/hide in respect to a bool on the associated ViewModel, but the following binding does not react on changes.

```csharp
<telerikGrid:DataGridTextColumn PropertyName="UniqueId" Header="UniqueId" IsVisible="{Binding ShowDeveloperDebugInfo, Mode=OneWay}" />
```
Shouldn't that work?

**Comment by APopatanasov** [comment]
Hi @byrialsen,

The DataContext of the DataGridColumn is the Column itself. In order to make the Binding work as expected you should add as source the desired ViewModel. I have created a sample project that demonstrates how to achieve this. Please, check it.
[RadDataGrid_349.zip](https://github.com/telerik/UI-For-UWP/files/2633891/RadDataGrid_349.zip)

**Comment by byrialsen** [comment]
Ahh, Thanks a lot for your time/sample. It makes sense.

**Comment by APopatanasov** [comment]
I am glad to hear it works. 😄
