### ISSUE TITLE
RadDataGrid - Nested DataGrid support

### ISSUE THREAD

**Issue by didi2391** [telerik/UI-For-UWP#354]
Is there a possibility to add 
1. An Expander control to each row of Data Grid 
2. On click of Expander icon for any row I need to display that row specific details in another data grid

I don't see any sample projects prevailing

Could you please help if this is supported currently

**Comment by APopatanasov** [comment]
Hi @didi2391 ,

The closest to your description functionality you can use is the row details of the DataGrid. On the following link you can find a detailed information about the feature:
https://docs.telerik.com/devtools/universal-windows-platform/controls/raddatagrid/features/row-details

And in the SDK examples section of the DataGrid an example could be found as well:
https://github.com/telerik/UI-For-UWP/tree/master/SDKExamples.UWP/Examples/Grid

Hope this will work for you.

**Comment by didi2391** [comment]
@APopatanasov -

I tried with the example provided by you for nested data grid support through Row details template and it works fine

But I have a scenario where in the inner grid would not be having static columns where in I have to load Dynamic columns from the Code Behind based on the Parent grid value selection

Is this scenario possible ?

**Comment by APopatanasov** [comment]
@didi2391 You can provide an x:Name for the DataGrid placed inside the RowDetails and simply use the Columns collection to add/remove columns dynamically as desired - for your particular scenario you need to handle the SelectionChanged event of the parent DataGrid and implement your logic inside it. 

As this issue is closed if you have any other issues that you are observing on your side please, open a new one - thus the communication will be separated and more easier to follow.
