### ISSUE TITLE
radcartesianchart lineseries last value not rendered if more than 9 series items

### ISSUE THREAD

**Issue by tabbed** [telerik/UI-For-UWP#366]
### Description
i tried to use a lineseries chart with 12 categories and two series. everything up to 9 items works fine.
if there are more than 9 items in each series always the last category is not rendered anymore

### Steps to Reproduce

1. create a radcartesianchart with 2 lineseries
2. add a dataset with 9 items in it and add the datasets as itemsources to the lineseries
3. test it
4. works
5. add another item to each dataset
6. test it again -> last item is not rendered

### Expected Behavior
all values are rendered

### Actual Behavior
all items up to a total count of 9 are rendered. as soon as the item count is higher than 10 the last item is not rendered anymore

### Basic Information

- Version with issue: 1.0.1.2
- Last known good version:
- IDE: Visual Studio 2017 Community
- UWP SDK: 16299
- Nuget Packages:

### Screenshots
![aef51c17-8fd8-430d-8da8-9fadf2b94fe3 png](https://user-images.githubusercontent.com/13349968/51269039-bfdfab80-19c1-11e9-91c4-92de590c32b0.jpg)

**Comment by APopatanasov** [comment]
Hi @tabbed ,

Using the provided description I have tried to reproduce the observed issue, but it seems everything is working as expected on my side.

Could you please, try to modify the attached project in order to reproduce the issue and send it back to me? Without being able to reproduce the issue on my side I will not be able to continue the investigation.

I am looking forward to hearing from you.
[RadChart_366.zip](https://github.com/telerik/UI-For-UWP/files/2767850/RadChart_366.zip)

**Comment by tabbed** [comment]
Hi,
I tried your example, and it worked as expected.
Then I realized that you missed to add the Category with Key "9".
I added the Category to both Lineseries, and the issue appeared.

[RadChart_366-modified.zip](https://github.com/telerik/UI-For-UWP/files/2780078/RadChart_366-modified.zip)

**Comment by APopatanasov** [comment]
Hi @tabbed ,

Thank you for modifing the project. I was able to reproduce the described by you issue. I will need some more time to investigate it in details. Once I have some more information to share I will let you know.
