### ISSUE TITLE
Sort string Numerically - RadDataGrid

### ISSUE THREAD

**Issue by didi2391** [telerik/UI-For-UWP#372]
I have certain columns where I have data's combined with Integer and string. So I made the data type as string

Example data before sorting: 
"1000V"
"1001V"
"1002V"
"159V"
"17V"
"13V"

Data after sorting:

"13V"
"1000V"
"17V"
"1001V"
"1002V"
"159V"

While sorting I need to consider only the integer and sort accordingly. Is it possible ?

**Comment by APopatanasov** [comment]
@didi2391 You can try to the DelegateSortDescriptor in order to achieve the desired sorting:
https://docs.telerik.com/devtools/universal-windows-platform/controls/raddatagrid/features/sorting/datagrid-delegatesortdescriptor

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased [a commercial license for UI for UWP](https://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed. You'll be directed to post your question on a community forum.
