### ISSUE TITLE
Customize the flyout appearance (Position and background) for default filter behaviour on RadDataGrid column header 

### ISSUE THREAD

**Issue by shrutidutt** [telerik/UI-For-UWP#394]
![image](https://user-images.githubusercontent.com/6298847/59605421-632d1c00-912c-11e9-8a33-790ccf0842c1.png)
Please see in the provided screenshot. How can I customize this flyout appearance (eg if I want to provide placement as right or set the margin so that it appears a little left, please see below screenshot for reference)

![image](https://user-images.githubusercontent.com/6298847/59605755-1564e380-912d-11e9-9f96-cbd097ac0142.png)

**Comment by APopatanasov** [comment]
Hi @shrutidutt ,

You can easily customize the default appearance of the DataGridFilteringFlyout using implicit styles:
`<Page.Resources>
    <Style TargetType="primitives:DataGridFilteringFlyout">
        <Setter Property="Background" Value="Red"/>
        <Setter Property="Padding" Value="16"/>
        <Setter Property="MinWidth" Value="190"/>
    </Style>
</Page.Resources>`

I don't suggest you to change the margin because that might result into an unexpected positioning of the Flyout. Instead you can play with the Max/MinWidth and Padding properties to achieve the desired positioning.

I will proceed and close the issue. Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased a[ commercial license for UI for UWP](https://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed. You'll be directed to post your question on [a community forum](https://github.com/telerik/UI-For-UWP/wiki/Getting-help).

Hope the answer is helpful for you.
