### ISSUE TITLE
Clearing grid filter state programmatically

### ISSUE THREAD

**Issue by jkewley** [telerik/UI-For-UWP#402]
### Description
Cross-posting from this [from my forum post on Telerik.com](https://www.telerik.com/forums/clearing-an-active-custom-filter-when-last-item-is-unchecked-uwp-grid).

I've implemented custom filtering based on [the how-to article in the KB](https://docs.telerik.com/devtools/universal-windows-platform/controls/raddatagrid/features/filtering/how-to/datagrid-howto-createcustomfilteringcontrol), but I see this odd behavior where, after clearing the last checkbox in my filter, the control appears to still run PassesFilter logic, resulting in 0 matches (no items match a filter with zero qualities to match on), and the column header still has the visual treatment indicating that it is filtered. What I'd like to do is have an un-check of the last item in a filter behave as if the user has clicked the 'Clear Filter' button. My challenge is that I can't find a way to clear the filter for a column from within a FilterRequested command

I've tried several things and have the following conclusions:

- The custom filter is applied to the column when the CommandId.FilterButtonTap command executes, but the Clear button executes CommandId.FilterRequested, so if I want to reset the filter I'd need to do so in my custom GridFilterRequestedCommand
- IsFiltering and Descriptor are both read-only properties on the FilterRequestContext in CommandId.FilterRequested so I can't try to set the first to false or null the second
- It looks like the Clear Filters button [removes the FilterDescriptor from the owner](https://github.com/telerik/UI-For-UWP/blob/2940a12f10527c564e5657fd92428656ebbb7dad/Controls/Grid/Grid.UWP/View/Services/Commands/FilterRequestedCommand.cs#L47), but this didn't make any difference when I tried it because [I can't un-set IsFiltering](https://github.com/telerik/UI-For-UWP/blob/2940a12f10527c564e5657fd92428656ebbb7dad/Controls/Grid/Grid.UWP/View/Services/Commands/FilterRequestedCommand.cs#L18)
- I can't create my own FilterRequestedContext to fake an invocation because of the internal sets on all the properties
- WPF appears to have a [ClearFilters method which UWP lacks](https://docs.telerik.com/devtools/wpf/controls/radgridview/filtering/programmatic#column-filtering)

I'm hoping there's some way to hack around these shortcomings. I also think that a CommandId.FilterRequested should be able to notify the Grid column filter that there are no items chosen to filter on, and that the column should act as if the filter has been cleared.

### Steps to Reproduce

1. Follow the KB article instructions
2. Check a value and apply the filter
3. uncheck the value and apply the filter. Zero results

### Expected Behavior
All records should be shown - no filtered items is logically equivalent to a cleared filter

### Actual Behavior
Zero results when no filter qualifiers are selected

### Basic Information

- Version with issue: Current
- Last known good version:
- IDE: VS 2019
- UWP SDK: 1809
- Nuget Packages: latest grid

**Comment by jkewley** [comment]
I ended up using reflection to force-set the IsFiltering property to false. That, combined with calling the default command for filter, was enough to achieve what I was after. I would still argue that this is a feature gap that should be remedied

**Comment by APopatanasov** [comment]
Hi @jkewley ,

The described by you behavior is not caused by the DataGrid control, but by the custom logic implemented in the article.

It is expected when the Apply button is pressed the command to execute filtering logic not the one for clearing. You can modify that behavior of the custom filtering ui by creating a custom FilterRequested command as you have already found out. Inside the Execute logic you can check if there are any checked items and only then to execute the default implementation of the command:

```
public class CustomApplyFilterCommand : DataGridCommand
{
    public CustomApplyFilterCommand()
    {
        this.Id = CommandId.FilterRequested;
    }

    public override bool CanExecute(object parameter)
    {
        return this.Owner.CommandService.CanExecuteDefaultCommand(CommandId.FilterRequested, parameter);
    }

    public override void Execute(object parameter)
    {
        var dataGrid = this.Owner;
        var context = (FilterRequestedContext)parameter;
        var descriptor = context.Descriptor as DelegateFilterDescriptor;
        if (descriptor != null)
        {
            var filter = descriptor.Filter as ColorFilter;
            if (filter != null && filter.Colors.Any(a => a.IsChecked))
            {
                dataGrid.CommandService.ExecuteDefaultCommand(CommandId.FilterRequested, parameter);
            }
        }
    }
}
```
The filter descriptor will be cleared when the apply is clicked and if there the default command is not executed no filter will be applied and thus the desired behavior will be achieved.

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased[ a commercial license for UI for UWP](https://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed.

Hope this will help you.
