### ISSUE TITLE
Datagrid: Change row color

### ISSUE THREAD

**Issue by MeindertRomkes** [telerik/UI-For-UWP#404]
Is it possible to change the color of a row in the datagrid? For example: the rows which have an errorMessage of null should just get the regular color, but the rows with an error message should be colored red.

**Comment by APopatanasov** [comment]
Hi @MeindertRomkes ,

You can use the **RowBackgroundSelector** property of the DataGrid control in order to apply specific Background color for the rows using some custom logic:

```
public class MyRowBackgroundSelector : ObjectSelector<Brush>
{
    protected override Brush SelectObjectCore(object item, DependencyObject container)
    {
        var person = (Item)item;
        if (person.Age < 20)
        {
            return new SolidColorBrush(Colors.Red);
        }

        return new SolidColorBrush(Colors.Blue);
    }
}
......
this.grid.RowBackgroundSelector = new MyRowBackgroundSelector();
```
Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased [a commercial license for UI for UWP](https://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repository, as these will be immediately closed.

Hope this helps.
