### ISSUE TITLE
ListView items

### ISSUE THREAD

**Issue by kinju4374** [telerik/UI-For-UWP#41]
Can RadListView load more than 4000 items easily as it has UI Virtualization?

**Comment by APopatanasov** [comment]
Hi @kinju4374,

Indeed the ListView is UI virtualized control and because of that you should not have any concerns about loading the desired by you number of items. 

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased a [commercial license for UI for UWP](http://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repo, as these will be immediately closed. You'll be directed to post your question on a community forum.
