### ISSUE TITLE
Rounding the bars in UWP

### ISSUE THREAD

**Issue by edsonmata** [telerik/UI-For-UWP#451]
## Summary
It would be nice to add the same feature that has in xamarin, which is rounding the bars.

As described in: https://docs.telerik.com/devtools/xamarin/nativecontrols/android/chart/series/chart-series-bar

e.g.

BarSeries barSeries = new BarSeries();
barSeries.AreBarsRounded = true;
barSeries.RoundBarsRadius = 10;

I wish I could do the same thing at UWP.

**Comment by APopatanasov** [comment]
Hi @edsonmata ,

The Chart control has two rendering mechanisms. [The first one is using the Composition APIs](https://docs.telerik.com/devtools/universal-windows-platform/controls/radchart/containervisualsfactory) to render the BarSeries and the second one is using native controls for rendering - for the concrete case with the BarSeries Borders are using.

The default mechanism is the one with the Composition and currently the visuals drawn by it do not support a corder radius. However, it is supported by the Border control.

So, in order to achieve the desired visualisation of the Bars first you need to switch to the native rendering by creating a custom ContainerVisualFactory and overriding the CanDrawContainerVisual method to return false. Next you need to set to the DefaultVisualStyle property of the series a Style that targets a Border and apply the desired CornerRadius. I have created a sample project that demonstrates the described approach - please, check it.

Hope this helps.
[RadChartUWP_451.zip](https://github.com/telerik/UI-For-UWP/files/4286864/RadChartUWP_451.zip)

**Comment by edsonmata** [comment]
Thank you very much for the details of the information.
This information helped me a lot.
