### ISSUE TITLE
I would like to add values previously informed on the y axis (UWP Bar or Line Charts)

### ISSUE THREAD

**Issue by edsonmata** [telerik/UI-For-UWP#452]
## Summary

Currently the graphs only support informing the major step to calculate the y axis. For example in the image below we have a "MajorStep = 3".

![image](https://user-images.githubusercontent.com/5148183/76239840-010fcc00-6211-11ea-9442-256a7605ec4a.png)

I would like to be able to inform a list or steps with different distances, for example: [0, 2, 10, 12].

**Note**: UWP bar and line graphs.

The graphic code informed in the image is:

````
<telerikChart:RadCartesianChart x:Name="barSeries" PaletteName="None">
            <telerikChart:RadCartesianChart.VerticalAxis>
                <telerikChart:LinearAxis MajorStep="3"/>
            </telerikChart:RadCartesianChart.VerticalAxis>
            
            <telerikChart:RadCartesianChart.HorizontalAxis>
                <telerikChart:CategoricalAxis/>
            </telerikChart:RadCartesianChart.HorizontalAxis>

            <telerikChart:BarSeries ItemsSource="{Binding}" PaletteMode="DataPoint" >
                <telerikChart:BarSeries.CategoryBinding>
                    <telerikChart:PropertyNameDataPointBinding PropertyName="Category"/>
                </telerikChart:BarSeries.CategoryBinding>
                <telerikChart:BarSeries.ValueBinding>
                    <telerikChart:PropertyNameDataPointBinding PropertyName="Value"/>
                </telerikChart:BarSeries.ValueBinding>
            </telerikChart:BarSeries>
        </telerikChart:RadCartesianChart>`

**Comment by APopatanasov** [comment]
@edsonmata In order to achieve the desired visualization of the labels you can use the LabelCreator functionality of the axis. 

You can set the MajorStep to 1 and implement some custom logic for the creator based on which you can decide which labels to be visualised. 

If you need to apply the same logic for the ticks I suggest you to use the MajorTickTemplate. For a Template a Rectangle could be set and using again a custom logic the Visibility could be set either to Visible or Collapsed.

I have prepared a sample project that demonstrates the described above approach - please, check it.

[RadChartUWP_452.zip](https://github.com/telerik/UI-For-UWP/files/4319474/RadChartUWP_452.zip)

**Comment by edsonmata** [comment]
Thank you very much for your support. I am very happy for the care with the details in your explanation.
