### ISSUE TITLE
DataGrid is not Accessibility-Friendly (Screen readers, keyboard-only users)

### ISSUE THREAD

**Issue by DhiMalo** [telerik/UI-For-UWP#457]
I downloaded the UI for UWP Demos app that showcases the controls. I was particularly interested in the DataGrid control. However, I was disappointed to discover the Datagrid (I particularly experimented with the one shown below) does not surface the expected accessibility experience for the Narrator or NVDA screen-reading tools. Additionally, it is not possible to use the keyboard to use filter buttons or select grid items. 

![image](https://user-images.githubusercontent.com/10456737/79253979-e1d01400-7e38-11ea-91e0-f02bec5fadbe.png)

**Comment by APopatanasov** [comment]
Hi @DhiMalo ,
The Telerik UI For UWP demos application that is currently available in the Windows Store hasn't been updated from a very long time - its last update is from March 2017. Since, then lots of improvements have been made for the accessibility features of the controls. That includes better support for the narrator, high contrast theme and keyboard support.

I suggest you to check the all these features by building an application using the DataGrid using our latest [nuget](https://www.nuget.org/packages/Telerik.UI.for.UniversalWindowsPlatform/). If you are interested on the demos application you can clone its [repository](https://github.com/telerik/UI-For-UWP-Demos) and update the nuget there as well. 

I hope the accessibility provided by the latest version of the controls will be suitable for your needs.

If there is an issue with the latest version of the controls, please open another issue describing in details the exact problem and what the expected behavior is.

Hope the provided information will be helpful for you.
