### ISSUE TITLE
How do I change the color of the rows in a raddatagrid when cycling through with keys. 

### ISSUE THREAD

**Issue by Going-Gone** [telerik/UI-For-UWP#469]
When using the key up or down, the highlight color of the row is gray. What is the name of the style that controls this color?

**Comment by APopatanasov** [comment]
@Going-Gone The observed highlight color comes from the DataGridCurrencyControl. In order to change it you can create an implicit style to set a different value for the BackgroundColor:
```xml
  <Style TargetType="gridPrimitives:DataGridCurrencyControl">
        <Setter Property="Background" Value="Red"/>
  </Style>
```

Please, also be aware that the UI for UWP team does not provide formal support, except to those customers who have purchased [a commercial license for UI for UWP](https://www.telerik.com/universal-windows-platform-ui). Please do not create support requests for this project in the issues list for this repository, as these will be immediately closed.
