### ISSUE TITLE
Windows.UI.Xaml.ResourceDictionary.Source Map control issue

### ISSUE THREAD

**Issue by RikardoPons** [telerik/UI-For-UWP#52]
I downloaded the code because I want to use map control.
I have this issue when I run my app.
I just added the control to the page.

The text associated with this error code could not be found.

Failed to assign to property 'Windows.UI.Xaml.ResourceDictionary.Source' because the type 'Windows.Foundation.String' cannot be assigned to the type 'Windows.Foundation.Uri'. [Line: 66 Position: 29]

**Comment by APopatanasov** [comment]
Hi @RikardoPons ,
I was able to reproduce the described issue. It was caused due to a missing ResourceDictionary file in the RadMap project. We have added it with [this ](https://github.com/telerik/UI-For-UWP/pull/53) pull request. Now everything should be working as expected. Could you please, pull the latest commit of the repository and let me know if now everything is working as expected?

**Comment by RikardoPons** [comment]
Hello I downloaded the pull request and now is working fine thank you!
