### ISSUE TITLE
Add Property to Disable RadSideDrawer

### ISSUE THREAD

**Issue by LanceMcCarthy** [telerik/UI-For-UWP#68]
There are scenarios where you would want to prevent the `RadSideDrawer` from opening, For example, the spacebar may unintentionally open the side drawer when the focus in within a `TextBox `or `Entry `(Xamarin Forms) control.

Currently, the only way to prevent this is to extend the `RadSideDrawer `and create a custom control that overrides `OnKeyDown`.

It would be useful to have an `IsDrawerEnabled `property.

**Comment by APopatanasov** [comment]
Hi @LanceMcCarthy ,

The observed by you behavior with the TextBox was actually a bug in the SideDrawer - it was introduced with the AutomationPeers implementation. The bug has already been fixed and a new command named **SideDrawerKeyDownCommand** was introduced. Using the command you can easily implement any desired logic when key gets pressed without the need of creating custom control in order to override the OnKeyDown method. #116 

Because of that the need of such property is no longer needed and I will close the request. However, if you have some other concerns why that property is needed now when there is a command please, let me know and I will consider reopening the issue.
