### ISSUE TITLE
When Telerik control on page Blend 2017 crashes on load of page

### ISSUE THREAD

**Issue by schnitty** [telerik/UI-For-UWP#96]
Steps to reproduce:

New blank project in VS2017
Add Telerik.UI.for.UniversalWindowsPlatform 1.0.0.2 nuget package
Add RadialGuage control to main page
Build
Open same project with Blend 2017

Just sits there loading the designer.  Ultimately never finishes, trying to load another page or cs file results in Blend 2017 crashing and restarting.

**Comment by schnitty** [comment]
It seems that v1.0.0.2 has introduces this.  Don't have the same issue with v1.0.01

**Comment by APopatanasov** [comment]
@schnitty I was able to reproduce the described by you issue. With version 1.0.0.2 we have made some improvements in our nuget package in order to make the controls be visualized in the toolbox when the nuget is referenced. It seems the issue is caused by that improvement. 

In order to make the controls work as expected in the designer again when opened in Blend you could delete the following xml file (VisualStudioToolsManifest.xml) from the folder of the nuget. Most commonly it is from the following location:
**C:\Users<username>\.nuget\packages\telerik.ui.for.universalwindowsplatform\1.0.0.2\tools\VisualStudioToolsManifest.xml**

We will investigate it further if the issue is caused from our side or by Blend. Also, as you have reported a similar issue with Visual Studio #97 that I wasn't able to reproduce I believe that both issues are connected-
ignore my answer there (#97) as no further information is needed for our investigation.

Thanks for bringing this to our attention. 😊
